name: my_finances
description: "App de finanzas personal con arquitectura modular"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  cloud_firestore: ^5.6.10
  connectivity_plus: ^6.1.4
  dartz: ^0.10.1
  dio: ^5.8.0+1
  equatable: ^2.0.7
  firebase_auth: ^5.6.1
  firebase_core: ^3.15.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  go_router: ^16.0.0
  injectable: ^2.5.0
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.3

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.5.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.5
  mockito: ^5.4.6

flutter:
  uses-material-design: true
